package com.ResearchHub.backend.model;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

// This class maps to the "users" collection in MongoDB
@Document(collection = "users")
public class UserModel {
  @Id
  private String id;
  private String username;
  private String email;
  private String password;

  // Default constructor (needed by Spring)
  public UserModel() {}

  // Parameterized constructor
  public UserModel(String username, String email, String password) {
    this.username = username;
    this.email = email;
    this.password = password;
  }

  // Getter for ID (auto-generated by MongoDB)
  public String getId() {
    return id;
  }

  // Getters for normal fields
  public String getUsername() {
    return username;
  }

  public String getEmail() {
    return email;
  }

  // ✅ Private access getter for password (used only internally)
  public String getPassword() {
    return password;
  }

  // Setters
  public void setUsername(String username) {
    this.username = username;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public void setPassword(String password) {
    this.password = password;
  }
}
